LONGREAD_FILE_TYPE: [fa/fa.gz/fasta/fasta.gz/fq/fq/gz/fastq/fastq.gz]
LONGREADS: [long-read_directory]
SHORTREADS: [short-read directory]
SHORTREAD_FILE_TYPE: [fa/fa.gz/fasta/fasta.gz/fq/fq/gz/fastq/fastq.gz]
PREFIX: [prefix]
REFERENCE_ASSEMBLY: ../resources/genomes/GCF_002263795.3_ARS-UCD2.0_genomic.fna.gz
REFERENCE_GFF: ../resources/genomes/GCF_002263795.3_ARS-UCD2.0_annotation.gff
OUTDIR: [results directory]
